### ISSUE TITLE
broken on Mac OS?

### ISSUE THREAD

**Issue by ghost** [vindarel/cl-readline#2] opened 2015-09-30 08:10 UTC
On Mac OS 10.9, SBCL 1.2.15, `(rl:readline :prompt "user>")` throws out:

```
Trying to access undefined foreign variable "rl_num_chars_to_read".
   [Condition of type SIMPLE-ERROR]
```

**Comment by mrkkrp** [comment] 2015-09-30 08:34
@macdavid313, Hi, thanks for the report, what is version of Readline?

**Comment by ghost** [comment] 2015-09-30 08:56
@mrkkrp How to check the version number? I think I'm using the most updated one, since I just `quickload` it today and `quicklisp` has just updated all dists recently.

**Comment by mrkkrp** [comment] 2015-09-30 09:02
@macdavid313, well, I'm asking about version of GNU/Readline library, this package is bindings for that library, so you should have it first, and it can be quite old.

Please evaluate symbol-macros `+library-version+` and `+readline-version+` from this package and report here their values.

**Comment by ghost** [comment] 2015-09-30 09:15
@mrkkrp `+library-version+` returns a string "EditLine wrapper", and `+readline-version+` return multiple values that are `4` and `2`.

**Comment by mrkkrp** [comment] 2015-09-30 09:24
@macdavid313, `4` and `2` means your version of Readline is `4.2`. Latest version is [6.3](https://en.wikipedia.org/wiki/GNU_Readline). `"EditLine wrapper"` also tells us that you probably using some sort of emulation of GNU/Readline.

Evaluate symbol-macro `+gnu-readline-p+` to be sure that this is emulation.

Please install GNU/Readline (should be available for Mac OS, as far as I know), this is bindings for that library, not for EditLine (which is GNU/Readline replacement under BSD-style license).

Hope it helps.

**Comment by mrkkrp** [comment] 2015-09-30 09:52
Closing this for now. Feel free to reopen if the problem is still there with recent versions of original GNU/Readline.

**Closed as completed by mrkkrp** 2015-09-30 09:52 UTC

**Comment by macdavid313** [comment] 2015-09-30 10:30
@mrkkrp Hi, thanks for you help. It's pretty weird that I do have a `GNU readline` of version 6.3 but still it doesn't work for me. I think it may be of some problem of system path issue. Anyway, I'll try to solve this and thanks for telling me that :)

**Comment by ghost** [comment] 2015-09-30 11:05
@mrkkrp Hi, thanks for you help. It's weird that I do have a `GNU readline` of version 6.3 but still it doesn't work. I guess it may be of the system PATH issue. Anyway, I'll try to fix it later and thanks for your great library :)
